services:
  postgres:
    image: postgres:16
    shm_size: "1gb"
    environment:
      POSTGRES_PASSWORD: GXMLkQLSAaoTkjod
      POSTGRES_USER: estimador
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: America/Sao_Paulo
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 127.0.0.1:6432:5432
    command:
      - postgres
      - -c
      - shared_buffers=1GB
      - -c
      - work_mem=64MB
      - -c
      - maintenance_work_mem=2GB
      - -c
      - effective_cache_size=1GB
      - -c
      - wal_level=replica
      - -c
      - wal_buffers=64MB
      - -c
      - max_wal_size=6GB
      - -c
      - max_connections=10
      - -c
      - max_worker_processes=4
      - -c
      - max_parallel_workers=4
      - -c
      - max_parallel_workers_per_gather=2
      - -c
      - autovacuum_work_mem=64MB
      - -c
      - random_page_cost=1.1
      - -c
      - effective_io_concurrency=200
      - -c
      - max_locks_per_transaction=512
      - -c
      - checkpoint_timeout=15min

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "127.0.0.1:6672:5672"
      - "127.0.0.1:25672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis
    container_name: redis
    ports:
      - "127.0.0.1:7379:6379"
    volumes:
      - ./cache:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: estimador_backend_charlie
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - postgres
      - rabbitmq
      - redis
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql+asyncpg://estimador:GXMLkQLSAaoTkjod@postgres:5432/estimador
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
